apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app-full-name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: '${{ values.storePath }}'
  tags:
    - library
    - ${{ values.app-full-name }}
spec:
  type: library
  lifecycle: experimental
  owner: ${{ values.owner }}
